services:
  - type: web
    name: ai-talker-backend
    runtime: python
    buildCommand: bash build.sh
    startCommand: cd backend && daphne -b 0.0.0.0 -p $PORT core.asgi:application
    rootDir: .
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PYTHONPATH
        value: backend
